name: Build RPM and DEB Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm dpkg-dev

    - name: Set up RPM build environment
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        
    - name: Prepare source tarball
      run: |
        mkdir admsys-1.0
        cp -r source admsys-1.0/
        tar -czvf ~/rpmbuild/SOURCES/admsys-1.0.tar.gz admsys-1.0

    - name: Create SPEC file
      run: |
        cat << EOF > ~/rpmbuild/SPECS/admsys.spec
        Name: admsys
        Version: 1.0
        Release: 1%{?dist}
        Summary: Script which count files in etcetra directory
        License: MIT
        Source0: %{name}-%{version}.tar.gz
        
        %description
        This package includes a script that counts files in the /etc directory.
        
        %prep
        %setup -q
        
        %build
        
        %install
        mkdir -p %{buildroot}/usr/local/bin
        install -m 755 source/counter.sh %{buildroot}/usr/local/bin/counter.sh
        
        %files
        /usr/local/bin/counter.sh
        
        %changelog
        EOF

    - name: Build RPM
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/admsys.spec

    - name: Prepare DEB package structure
      run: |
        mkdir -p ~/admsys_1.0-1/usr/local/bin
        cp source/counter.sh ~/admsys_1.0-1/usr/local/bin/
        mkdir ~/admsys_1.0-1/DEBIAN

    - name: Create DEB control file
      run: |
        cat << EOF > ~/admsys_1.0-1/DEBIAN/control
        Package: admsys
        Version: 1.0-1
        Section: base
        Priority: optional
        Architecture: all
        Maintainer: Nesquick <Nesquick@example.com>
        Description: Script which count files in etcetra directory
         This package includes a script that counts files in the /etc directory.
        EOF

    - name: Set permissions for DEB package
      run: |
        chmod 755 ~/admsys_1.0-1/usr/local/bin/counter.sh

    - name: Build DEB package
      run: |
        dpkg-deb --build ~/admsys_1.0-1

    - name: Upload RPM as artifact
      uses: actions/upload-artifact@v3
      with:
        name: admsys-rpm
        path: ~/rpmbuild/RPMS/x86_64/*.rpm

    - name: Upload DEB as artifact
      uses: actions/upload-artifact@v3
      with:
        name: admsys-deb
        path: ~/admsys_1.0-1.deb
